services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    environment:
      DJANGO_SETTINGS_MODULE: config.django.dev
    networks:
      - backend
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173" # vite's port
    volumes:
      - ./frontend:/app
      - /app/node_modules # avoids problems with node_modules
    depends_on:
      - backend
    networks:
      - frontend
      - backend 

networks:
  backend:
  frontend:
